import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { AnalysisResult } from "./analysisEngine";

export function generateReport(result: AnalysisResult) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header bar
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 35, "F");

  doc.setTextColor(0, 240, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("ForensiX AI", 14, 18);

  doc.setTextColor(148, 163, 184);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Forensic Intelligence Report", 14, 26);

  doc.setTextColor(148, 163, 184);
  doc.text(`Case ID: ${result.caseId}`, pageWidth - 14, 18, { align: "right" });
  doc.text(`Date: ${new Date(result.analyzedAt).toLocaleDateString()}`, pageWidth - 14, 26, { align: "right" });

  // Verdict section
  const isForged = result.verdict === "FORGED";
  doc.setFillColor(isForged ? 127 : 34, isForged ? 29 : 120, isForged ? 29 : 60);
  doc.roundedRect(14, 42, pageWidth - 28, 22, 3, 3, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`VERDICT: ${result.verdict}`, 22, 54);

  doc.setFontSize(10);
  doc.text(`Confidence: ${result.confidence}%`, pageWidth - 22, 54, { align: "right" });

  // Document info
  let y = 74;
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Document Information", 14, y);
  y += 8;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  const info = [
    ["File Name", result.fileName],
    ["File Size", `${(result.fileSize / 1024).toFixed(1)} KB`],
    ["File Type", result.fileType],
    ["Analyzed At", new Date(result.analyzedAt).toLocaleString()],
    ["Highest Risk Module", result.highestContributor],
  ];
  info.forEach(([label, val]) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, 14, y);
    doc.setFont("helvetica", "normal");
    doc.text(val, 60, y);
    y += 6;
  });

  // Score breakdown table
  y += 6;
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Score Breakdown", 14, y);
  y += 4;

  autoTable(doc, {
    startY: y,
    head: [["Module", "Weight", "Score", "Weighted Score", "Risk Level"]],
    body: result.scoreBreakdown.map((b) => [
      b.module,
      `${(b.weight * 100).toFixed(0)}%`,
      `${(b.score * 100).toFixed(1)}%`,
      `${(b.weighted * 100).toFixed(2)}%`,
      b.score > 0.6 ? "HIGH" : b.score > 0.35 ? "MEDIUM" : "LOW",
    ]),
    theme: "grid",
    headStyles: { fillColor: [15, 23, 42], textColor: [0, 240, 255], fontSize: 8 },
    bodyStyles: { fontSize: 8, textColor: [51, 65, 85] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { left: 14, right: 14 },
  });

  // Explanation
  const finalY = (doc as any).lastAutoTable?.finalY || y + 40;
  let ey = finalY + 12;
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("AI Explanation", 14, ey);
  ey += 8;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  const lines = doc.splitTextToSize(result.explanation, pageWidth - 28);
  doc.text(lines, 14, ey);
  ey += lines.length * 5 + 10;

  // Evidence
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Metadata Evidence", 14, ey);
  ey += 8;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  result.metadata.metadata_evidence.forEach((ev) => {
    doc.text(`• ${ev}`, 18, ey);
    ey += 5;
  });

  // Footer
  ey += 15;
  doc.setDrawColor(226, 232, 240);
  doc.line(14, ey, pageWidth - 14, ey);
  ey += 10;
  doc.setTextColor(148, 163, 184);
  doc.setFontSize(7);
  doc.text("This report was generated by ForensiX AI — Intelligent Document Fraud Detection Platform", 14, ey);
  doc.text("Investigator Signature: _________________________", 14, ey + 10);
  doc.text(`Report ID: ${result.caseId} | Generated: ${new Date().toISOString()}`, 14, ey + 20);

  doc.save(`ForensiX-Report-${result.caseId}.pdf`);
}
